platform :ios, '9.0'

target 'KosuApp' do
use_modular_headers!

  pod 'RealmSwift'

  target 'KosuAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KosuAppUITests' do
    # Pods for testing
  end

end
