//
//  VeriSeti.swift
//  KosuApp
//
//  Created by Sedat on 14.12.2022.
//

import Foundation

class VeriSeti{
    
    let kategoriler = [
    
        OneriKategori(kategoriAdi: "Aksiyon", goruntuAdi: "kategoriAksiyon"),
        OneriKategori(kategoriAdi: "Animasyon", goruntuAdi: "kategoriAnimasyon"),
        OneriKategori(kategoriAdi: "Bilim-Kurgu", goruntuAdi: "kategoriBilimKurgu"),
        OneriKategori(kategoriAdi: "Dram", goruntuAdi: "kategoriDram"),
        OneriKategori(kategoriAdi: "Komedi", goruntuAdi: "kategoriKomedi"),
        OneriKategori(kategoriAdi: "Korku", goruntuAdi: "kategoriKorku")
    ]
    
    
    let komediFilmleri = [
            Oneri(adi: "Click", detaylari: " Bir mimar olan Micheal Newman'ın tipik bir orta sınıf ailesi vardır. Sevgi dolu, eşsiz karısı Donna, oğulları Ben ve kızları Samantha ve bir de sabit ziyaretçileri olan kendi ebeveynleri ile mutlu bir yaşamları vardır. Ancak Micheal tam bir işkoliktir. Sürekli stres altında, patronunu tatmin ederek şirkette bir ortaklık payı elde etmek ister. Bu sırada işine fazla önem verdiği için de ailesini ihmal eder. Micheal bir gün uzaktan kumanda satın almak üzere girdiği bir dükkânda tuhaf bir satıcı olan Morty ile tanışır. Morty kendisine hayatını kumanda edebilecek bir kumanda aleti sunar. Micheal aleti çok kullanarak aletin kumandasını kaybeder. Bu sayede hayatının değerini farkına varacaktır.", goruntuAdi: "click"),
            Oneri(adi: "Dumb and Dumber ", detaylari: "Llyod Christmas ve Harry Dunne kirli ve dağınık bir evde yaşayan, sık sık işlerinden kovulan birbirinden avanak iki arkadaştır. Llyod Rhode Island'da limuzin şoförlüğü yapmakta iken bir gün güzel ve zengin bir kadın olan Mary Swanson'ı hava alanına götürür, bu esnada ona aşık olur. Mary hava alanında bir çanta unutur, çantayı alan Llyod Mary'nin gözüne girme umuduyla çantasını ona geri götürmeyi kafasına koyar. Llyod malum sebeplerle Mary'nin ulaşacağı uçağa yetişmeyi beceremez. Bunun üzerine ikili Harry'nin yeni (ve başarısız) köpek işi için bir köpek şeklinde dekore ettiği kamyonuyla Mary'i Aspen'da bulmaya çalışır. Bilmedikleri gerçek ise çantanın parayla dolu olduğu ve Mary'nin onu hava alanında kaçırılan kocasının hayatını kurtarmak için fidye olarak bıraktığıdır", goruntuAdi: "dumbanddumber"),
            Oneri(adi: "AROG", detaylari: "G.O.R.A gezegeninde tutsak olan Arif'e büyük kin besleyen Komutan Logar, onu zaman makinesiyle bir milyon yıl öncesine gönderir. Taş Devri insanları, dinozorlar ve prehistorik kuşların yer aldığı AROG'da Arif'in yeni maceralarını izleyeceğiz.", goruntuAdi: "arog"),
            Oneri(adi: "Vizontele", detaylari: "Sene 1974. Van'ın Gevaş ilçesi. Köyün futbolcu delikanlısı Rıfat askere gidiyor. Sevgilisi Asiye ise gururlu bir kız. Üzüldüğünü göstermek istemiyor.Köyün delisi Emin'se teknoloji meraklısı. Ama kontrol edemediği bir tiki var. Başkalarının hareketlerini tekrar etmek. Tüm köy halkı sinemayla yatıp sinemayla kalkıyor. Bir gün TRT'den bir ekip köye TV vericisi getirmek için geliyor ama işi ciddiye almıyor. Deli Emin'se televizyon olayını onur meselesi yapıyor ve bu yolda tek destekçisi ilçenin belediye başkanı Nazmi Bey.", goruntuAdi: "vizontele"),
            Oneri(adi: "Aile Arasında", detaylari: "Çok takıntılı bir adam olan Fikret (Engin Günaydın) ve müzikhol vokalisti Solmaz (Demet Evgar), aynı gün yıllar süren evliliklerini bitirmiş, ve çok tuhaf olaylar sonucunda karşılaşmışlardır. Bu sırada Solmaz'ın kızı Zeynep, zengin bir kebapçının oğluyla evlenmeye karar vermiştir. Ancak ilk başta aile arasında olması planlanan nikah, giderek tantanalı bir hal alınca Fikret kendini hiç beklemediği olayların ortasında bulacaktır.", goruntuAdi: "ailearasinda"),
            Oneri(adi: "The Hangover", detaylari: "Filmde arkadaşlarının düğününden iki gün önce bekarlığa veda partisi vermek için Las Vegas'a giden dört tuhaf arkadaşın, sarhoş oldukları parti gecesinin sabahında odalarında bir kaplan, tavuklar ve dolapta ağlayan altı aylık bir bebek ile uyanmaları üzerine gelişen olağanüstü maceralar aktarılmaktadır. Damadın ortalıkta olmaması da ayrı bir meseledir! Kafaları hala kıyak olan bu kafadarlar, bir gece öncesine dair hiçbir şeyi hatırlayamazlar. Birbirinden şapşal ama sevimli bu üç hergele, ipuçlarını takip ederek işlerin nerede kontrolden çıktığını bulmak zorundadırlar. En önemlisi de damadı bularak zamanında Los Angeles'a düğününe yetiştirmeleri gerekmektedir.", goruntuAdi: "thehangover"),
            Oneri(adi: "The Blues Brothers", detaylari: "Jake Blues hapisten çıkar çıkmaz kardeşi Elwood ile birlikte eski öğretmenleri Rahibe Mary Stigmata'ya koşar ve korkunç gerçeği öğrenir: birlikte büyüdükleri yetimhane yokolmaktan kurtarmak için tam 5000 dolara ihtiyaç vardır. Jake ve Elwood bunun üzerine eski müzisyen arkadaşlarını bir araya toplayarak bir konser vermeye karar verirler. Bunu yaparken Şikago'nun altını üstüne getirecekler, peşlerinde tüm bir polis filosu ve naziler olduğu halde müthiş bir serüvene girişecekler. Siyahi müziği ile büyümüş iki beyazı canlandıran John Belushi ve Dan Aykroyd'a bu müthiş müzikalde James Brown, Aretha Franklin, Ray Charles, John Candy, Carrie Fisher ve Steve Lawrence gibi sayısız ünlü isim eşlik ediyor. Yönetmen John Landis'in bu kez yanında Belushi olamadan 1998'de kalkıştığı devam filmi, Cazcı Kardeşler 2000'in aynı başarıyı yakalayamadığını ekleyelim.", goruntuAdi: "thebluesbrothers"),
            Oneri(adi: "Shaun of the Dead", detaylari: "Bir adam can çekişmekte olan hayatını kurtarmaya karar verir. İlk adım olarak da eski kız arkadaşını yeniden kazanmayı planlar. Annesi ile olan ilişkisini düzeltmek ister. Bir gün Kuzey Londra'yı zombiler basar. Sokaklarda ölüler birikmeye başlar. Bütün bunları izleyen Shaun, sevdiklerini kurtarmaya karar verir. Liz, Ed, Pete ve annesini toparlayıp Winchester'a ulaşabilirse hayatta kalacaklarına inanan Shaun'u zorlu bir macera beklemektedir.  Annesi bir zombi tarafından ısırılır. Shaun onu öldürmek zorunda kalır. Film aslında bir zombi komedisi. Eleştirmenler tarafından oldukça övgü almıştır.", goruntuAdi: "shaunofthedead"),
            Oneri(adi: "City Lights", detaylari: "Kör bir çiçekçiye aşık olan ve sokaklarda yaşayan iyi niyetli bir serseri, kıza kendisini varlıklı biri olarak tanıtır. Bir milyonerin hayatını kurtarmıştır ve onun kendisine yardım edeceğine güvenmektedir. Adamı ziyaret edip sevdiği kızın gözlerini ameliyat ettirebilecek kadar para ödünç alabileceğini düşünür. Ama zengin insanlar aslında ikiyüzlü bir yaşam sürmektedirler", goruntuAdi: "citylights"),
            Oneri(adi: "Pardon", detaylari: "Tiyatro fenomeni, yazar, meddah ve sinemacı Ferhan Şensoy'un, gerçek bir olaydan esinlenerek sinemaya aktardığı bu ilginç film, üç yakın arkadaşın talihsiz hayatlarının hikayesi. Sıradan birer vatandaş olan üç kafadarın yaşamı, içlerinden birinin bir hatası yüzünden tamamen değişecektir. Her zamanki gibi akıp giden günler artık hiçbir zaman eskisi gibi olmayacaktır. Vaktinden çok sonra askerliğini yapan İbrahim nerede bir resmi kıyafet görse hemen oradan kaçar olmuştur. Sadece masum bir korku gibi gözüken bu fobisi yüzünden sevdiği arkadaşları ve kendisinin başına gelmeyen kalmaz. Arkadaşlarıyla beraber kendini mahkeme salonlarından, hapishaneye kadar uzanan bir yolculukta bulur. Neler olup bittiğini anlamadan cezaevine düşen, üç arkadaşın akılları hep dışarıdadır. Ama geride kalanlar yavaş yavaş kendi yollarını çizmektedir.", goruntuAdi: "pardon"),
            Oneri(adi: "Vizontele", detaylari: "En büyük eğlence kaynağı, herkesin büyük ilgi gösterdiği yazlık sineması olan bir kasaba… Kasabanın deli oğlanı Emin, çevresindeki tüm insanlara her türlü işte yardım eden ve herkesin sevdiği bir adamdır. Televizyonun henüz yeni yeni Anadolu'ya yayılmaya başladığı bu dönemde köy halkı dönemin en büyük icadıyla tanışmaya hazırlanmaktadır. Televizyona dair çeşitli beklentiler vardır. Mekanik işlerle uğraşmayı seven Emin de televizyonun nasıl bir buluş olduğunu merak etmektedir. Televizyon kasabaya gelirken, beraberinde birçok şey getirecektir... Yılmaz Erdoğan'ın gösterildiği dönemde hasılat rekorları kıran filminin başrollerinde de Erdoğan'ın yanısıra Demet Akbağ, Cem Yılmaz, Tarık Akan ve Erdal Tosun gibi isimler var", goruntuAdi: "vizontele"),
            Oneri(adi: "3 idiots", detaylari: "Rancho Chhanched, Farhan Qureshi ve Raju Rastogi Hindistan'ın en önemli bir okulunda mühendislik okuyan ve okulun yurdunda aynı odada kalan üç öğrencidir. Raju ailesini fakirlikten kurtarma gibi bir ideale sahipken Farhan ailesinin isteği doğrultunda bu bölümü seçmiştir. Rancho ise makinelere duyduğu tutku nedeniyle mühendis olmayı istemektedir. Bu üçlü ve profesörleri Viru arasında yaşananlar, dostluk kavramını beyaz perdeye yansıtırken eğitim sistemini de sert ve eğlenceli bir şekilde eleştirir niteliktedir. Son dönemin fazlasıyla dikkat çeken yapıtlarında biri olan film Hindistanın en çok izlenen filmlerden biri olurken özellikle Amerika'da da bir hayli dikkat çekmişti.", goruntuAdi: "idiots"),
            Oneri(adi: "GORA", detaylari: "Kurnaz ve genç bir adam olan Arif, bir kasabada halı satarak yaşamını sürdürmektedir. Genelde yaşadığı bölgedeki insanlar, kendisini hafif üç kağıtçı bir tip olarak bilirler. Bir gün Arif'in dükkanına gelen yabancı müşteriler, ona hayal bile edemeyeceği bir deneyim yaşatır. Gelenler aslen uzaylılardır ve bu uzaylılar tarafından kaçırılan Arif, bambaşka bir gezegene götürülür. Arif, karakterine uygun bir biçimde bu gezegenden kaçıp kurtulabilmenin türlü yollarını aramaya başlar. Ancak yaşayacağı maceralar, onun bu gezegende aşk ile burun buruna gelmesine de neden olacaktır. Cem Yılmaz'dan kahkaha dolu dakikalar.", goruntuAdi: "gora"),
            Oneri(adi: "Tosun Paşa", detaylari: "Osmanlı döneminde iki düşman aile olan Tellioğulları ve Seferoğulları, Yeşilvadi adındaki bölge için rekabet halindedir. İki aile, vadiyi ele geçirebilmek için Daver Bey adlı üst düzey bir devlet memurunun kızı Leyla'yı oğullarına isterler ve Daver Bey kızını Seferoğulları'na vermeye karar verir. Hal böyle olunca Tellioğulları da evin uşağı Şaban'ı en sözü geçen paşa olan Tosun Paşa kılığına sokar. Fakat ne yazık ki Şaban Leyla'ya âşık olur ve her şeyi mahveder. Gerçek Tosun Paşa gelince de işler iyice karışır. Oyuncu ve yönetmen Kartal Tibet'in yönetmenliğini üstlendiği yapım, bol güldürü unsurları içeren, eğlenceli ve kadrosu sağlam bir film.", goruntuAdi: "tosunpasa"),
        ]
        
        let aksiyonFilmleri = [
            Oneri(adi: "Rambo First Blood", detaylari: "John Rambo,bir dağ kasabasına gelirken kasaba şerifinin taciziyle karşılaşır. Tek istediği temizlenmek ve karnını doyurmaktır. Şerif ona terörist muamelesi yapar, yakalar, hapse atar. Hapiste polislerin işkencesi sırasında Rambo'nun gözünde Vietnam'da gördüğü işkenceler canlanır ve karakolu darmadağın edip bir motosiklete el koyarak dağa kaçar.", goruntuAdi: "rambofirstblood"),
            Oneri(adi: "The Bourne Ultimatum", detaylari: "Oscar ödüllü Matt Damon, kalifiye bir suikastçi olan Jason Bourne'u canlandırıyor. Genç ve son derece profesyonel yeni yetişmiş katiller, hafızasını ve hayatta sevdiği tek insanı kaybeden Bourne'u kurşunlarıyla yıldırmaya çalışıyor, her hareketini izliyor ve her ne pahasına olursa olsun, gerçek kimliğini öğrenmesini engellemeye çalışıyorlar.", goruntuAdi: "thebourneultimatom"),
            Oneri(adi: "Wanted", detaylari: "Babasının kiralık katil olduğunu öğrenen ve onun izinden gitmeye karar veren heyecanlı bir genç olan Wes, kendisine mesleğin inceliklerini öğretecek olan Fox ve Sloan adlı deneyimli katiller hamiliğinde çalışmaya başlar. Hayatında oldukça başarısız olan ve bu döngüyü kırmak isteyen Wes, Fox'u tanıdığı günden itibaren bakış açısını değiştirerek benliğinin içinde sinsi sinsi dolaşan kızgın ve öfkeli kurdu serbest bırakacaktır.", goruntuAdi: "wanted"),
            Oneri(adi: "Casino Royale", detaylari: "Bir bombalama olayının tüm IMF takımına yıkılmaya çalışılmasının ardından, Ethan Hunt ve ekibi sıra dışı bir göreve çıkıyor. Tehlike hiç bu kadar yüksek, aksiyon hiç bu kadar hararetli, Görev hiç bu kadar tehlikeli olmamıştı!", goruntuAdi: "casinoroyale"),
            Oneri(adi: "Enemy of the State", detaylari: "Güç savaşları nedeniyle Amerikan hükümetinde meydana gelen bir cinayet, olayla ilişkisi olmayan kişileri bile çembere dahil ederek tehlikeye sürükler. Cinayeti tesadüf eseri kaydeden doğa araştırmacısı Daniel Zavitz, kaydı kopyalayarak esrarengiz bir gazeteciyle iletişime geçer. Bunu öğrenen istihbarat servisi Zavitz’in peşine düşer ve adam eski bir arkadaşı olan avukat Robert Dean’e gider. Zavitz elindeki delil cd’sini gizlice Dean’in çantasının içine atar. Cd’nin kimde olduğunu öğrenen hükümetin istihbarat servisinin tehlikeli ajanları tüm imkanlarını seferber ederek Dean’in çevresini sarıp sarmalayarak kaçmasını imkansız kılmaya çalışacaklardır. Hollywood’un macera-aksiyon filmlerinde özgün olmayı başarabilmiş yönetmenlerden biri olan Tonny Scott tarafından yönetilen film politik okumalara da son derece müsait.", goruntuAdi: "enemyofthestate"),
            Oneri(adi: "The Spy Who Dumped Me", detaylari: "2 gün boyunca aksiyon dolu maceralara atılan Audrey ve Morgan'ın hikayesini anlatıyor. 30'lu yaşlarında olan Audrey ve Morgan, birbirlerinin en yakın arkadaşıdır. Los Angeles'ta sürdürdükleri hayat, sakin olsa da ikisini de tatmin etmez. Öne çıkan hiçbir noktası olmayan sıradan hayatları, Audrey'in eski sevgilisinin bir anda evlerine gelmesiyle karışır. Peşinde ölümcül suikastçılar olan bu adam, iki kadının hayatını altüst eder. Eski sevgilisinin ajan olduğunu öğrenen Audrey ve ona yoldaşlık etmeye kararlı olan Morgan, kendilerini bile şaşırtarak maceraya atılırlar. Avrupa boyunca peşlerindeki suikastçılardan kaçan ekip, bu süreçte dünyayı kurtaracak bir plan yapmak zorundadır. Uluslararası bir komploya karışan ikilinin her şeyi çözmek için zamanı bir hayli kısıtlıdır.", goruntuAdi: "thespywhodumpedme"),
            Oneri(adi: "Mad Max 2", detaylari: "Nükleer savaş sonrası harap ve bitap düşmüş Avustralya. İlk filmden hatırladığımız çılgın Max, ailesini kaybettikten sonra kendisini yollara vurmuştur. İnsanların ulaşımlarını sağlayacak petrol için yaşadığı bir bölgede çetelerin baskısı altında olan bir grubun yanına sığınır ve güvenliklerini sağlamaya çalışır. Pek çok kaynakda ilk filmden daha başarılı bulunan devam filmi Yol Savaşcısı, bilim kurgu-western-kara film arasındaki sınırları flu'laştırarak, oldukça etkileyici bir çalışma ortaya çıkarıyor. Filmin başarısından sonra pek çok taklidi yapıldı. Başarısız bir film olan, Su Dünyası?da Mad Max'in devam filmi Road Warrior'un izlerini taşır.", goruntuAdi: "madmax2"),
            Oneri(adi: "Taken", detaylari: "", goruntuAdi: "taken"),
            Oneri(adi: "Avengers: Infinity War", detaylari: "Kaptan Amerika ve Iron Man'in arasında yaşanan olayların ardından bölünen kahramanlarımız, birbirlerinden uzaklara savrulurlar. Hepsi kendi yandaşlarıyla dünyayı korumaya çalışırlar. Ancak dünyanın kaderi bir kez daha tehlikeye girer. Sınırsız bir güç kaynağı olan sonsuzluk taşlarının peşine düşen Thanos, dünyanın gördüğü en büyük tehdittir. İnsanlığın kaderi bir kez daha, insanlık için savaşmaya ant içmiş kahramanlarımızın elindedir. Hiçbir süper kahramanın tek başına yenemeyeceği büyüklükteki bu tehdit için ekipler birleşip, tehdide tüm güçleriyle karşı koymaya başlarlar.", goruntuAdi: "avengersinfinitywar"),
            Oneri(adi: "Annihilation", detaylari: "Gerçekleşen anormal faaliyetlerden dolayı hükumet tarafından gizlice karantinaya alınan gizemli Area X bölgesi, on yıllardır kıtanın geri kalanından ayrıdır. Doğa, insan uygarlığının son izlerini de bölgeden silmiş durumdadır. İlk keşif gezisi, bozulmamış, cennet gibi bir doğanın süregeldiğini rapor eder. Bölgeye giden 2. keşif grubu toplu intiharla, 3. keşif grubu dost ateşiyle, en sonuncu olan 11. keşif grubu ise kendilerinin bir gölgesi olarak geri dönmüş ve kısa süre sonra kanserden ölmüştür. 12. keşif grubunu oluşturan bir biyolog, bir antropolog, bir psikolog ve bir araştırmacı, kendilerini nelerin beklediğini bilmeden bölgeye giriş yapar. Görevleri araziyi haritalamak, örnek toplamak ve bütün gözlemlerini raporlamaktır. Akıl almayacak topografik anomalilere ve yeni yaşam biçimlerine şahit olan ekibin birbirlerinden sakladıkları sırların ortaya çıkması ise her şeyi değiştirecektir.", goruntuAdi: "annihilation"),
            Oneri(adi: "Undisputed III: Redemption", detaylari: "Yeni cezaevi turnuvası başlıyor. Rus mahkum Boyka, Yenilmez 2′nin sonunda dizinden sakatlandığı için hayatına sakat bir bacakla devam etmektedir. Artık dövüşlerle katılmayıp tuvalet temizliği yapmaktadır. Ama bu yeni cezaevi turnuvası uluslararası bir turnuva haline gelmiştir.", goruntuAdi: "undisputed3redemption"),
            Oneri(adi: "Crank", detaylari: "Chev Chelios güne beklenmedik bir uyandırma telefonuyla başlamak üzeredir. Sersem vaziyette, zorlukla hareket eden, kalp atışları bile yavaşlamış olan Chev, çalan cep telefonunu açtığında, katil düşmanı Ricky Verona'dan uykusu sırasında zehirlendiğini ve sadece bir saat ömrü kaldığını öğrenir.", goruntuAdi: "crank")
        ]
        
        let animasyonFilmleri = [
            Oneri(adi: "Rango", detaylari: "Kişilik problemi yaşayan oyuncu bir bukalemun'un başrolde olduğu bu eğlenceli animasyon, tatsız ve kötü şeylerden hep sakınan ve sıradan bir evcil hayvan hayatı yaşayan bukalemun Rango'nun başından geçen dönüşüm hikayesini anlatıyor. \"Sonuçta hayattaki tek amacınız kalabalığa uyum sağlamaksa hedefiniz ne kadar yüksekte olabilir ki?\" sloganıyla tanıtılan filmde Rango, kendini birden gözüpek kanunsuzların ve eşkıyaların olduğu, sakinlerini çölün en üçkağıtçı ve sahteler yaratıklarının oluşturduğu Toprak kasabasında bulunca, cesur diyemeyeceğimiz bu bukalemun dikkat çektiğini fark eder. Kasabanın yıllardır heyecanla beklediği umudu olarak sevinçle karşınan Şerif Rango, yeni rolüne uyum sağlamaya mecbur kalır. Fakat kendini aksiyon dolu durumlarla, ürkütücü karakterlerle yüzyüze bulması uzun sürmez. Eskiden numarasını yaparken şimdi kahraman olmaya başlayan Rango, kendini ve zamanla da kasabayı kurtaran bilindik klasik yabancı western efsanesine heyecan verici yeni bir boyut katıyor.", goruntuAdi: "rango"),
            Oneri(adi: "Kung Fu Panda", detaylari: "Beş yıldan uzun süren bir çalışma sonucunda ortaya çıkan animasyon harikası Kung Fu Panda'nın üç sloganı var: \"Kendi kahramanın ol!\", \"Panda-mania başlıyor!\" ve \"Çok muhteşem olacak!\" Kung Fu fanatiği panda Po, Huzur Vadisi'ni Kar Leoparı Tai Lung'dan kurtarmak için Kung Fu dünyasına adım atar. Çevresine göre bu iş için biraz fazla kilolu ya da beceriksiz olabilir! Ancak zamanla kendisine inandığı takdirde neler yapabileceğini keşfeder.Mark Osborne ile John Stevenson'ın birlikte yönettiği Oscar adayı filmin orijinal seslendirme kadrosunda Jack Black, Ian McShane, Angelina Jolie ve Ian McShane gibi ünlü isimler bulunuyor.", goruntuAdi: "kungfupanda"),
            Oneri(adi: "Mary And Max", detaylari: "Babasının kiralık katil olduğunu öğrenen ve onun izinden gitmeye karar veren heyecanlı bir genç olan Wes, kendisine mesleğin inceliklerini öğretecek olan Fox ve Sloan adlı deneyimli katiller hamiliğinde çalışmaya başlar. Hayatında oldukça başarısız olan ve bu döngüyü kırmak isteyen Wes, Fox'u tanıdığı günden itibaren bakış açısını değiştirerek benliğinin içinde sinsi sinsi dolaşan kızgın ve öfkeli kurdu serbest bırakacaktır.", goruntuAdi: "maryandmax"),
            Oneri(adi: "Brave", detaylari: "Merida, Kral Fergus ve Kraliçe Elinor’un okçuluk konusunda oldukça yetenekli ama bir kadar da deli fişek kızlarıdır. Kaderinin kendi elinde olduğuna inan Merinda, ülkede yüzyıllardan beri gelen bir geleneğe karşı çıkar. Lord MacGuffin, Lord Macintosh ve Lord Dingwall bu yetenekli, kızıl saçlı kızdan hiç hoşlanmazlar ve Merida’nın kararları krallık içerisindeki düzeni bozar. Bilge Kadın’a başvurduğunda ise uğursuz bir dileğin onu beklediğini öğrenir. Merinda ardı sıra gelen tehlikeli güçlerin farkına varır ve daha fazla gecikmeden korkunç laneti ortadan kaldırmaya çalışırken bir ayndan da gerçek cesaret ile yüzleşir... İnanılmaz Aile, Ratatouille gibi başarılı aninasyonlarda imzası olan Mark Andrews ve Aslan Kral'ı da yöneten Brenda Chapman'ın ortak yönetmenliğinde çekilen film, tam bir Pixar klasiği olmaya aday. Film Disney Digital 3D™ teknolojisiyle gösterime girecek.", goruntuAdi: "brave"),
            Oneri(adi: "The Illusionist", detaylari: "2010 yapımı Sylvain Chomet tarafından yönetilmiş animasyon komedi dram filmidir. Film, Fransız pandomim sanatçısı, yönetmen ve aktör Jacques Tati tarafından 1956'da yazıya alınmamış bir senaryosundan uyarlandı", goruntuAdi: "theillusionist"),
            Oneri(adi: "Sita Sings The Blues", detaylari: "Hindistan'ın Ramayana destanından tanrıça Sita, on dört senelik bir sürgünde olan kocası Rama'yı ormanlarda ararken, kötü kalpli Sri Lanka kralı tarafından kaçırılır. Kocasına sadık kalan Sita, zorlu sınavlardan geçer. Nina da kocasının iş için gittiği Hindistan'da ondan boşanmaya karar verip ve bunu bir postayla bildirmesinin üzerine evliliğini kurtarma savaşına girmiştir. Kendi hikâyesinin ve Sita'nın hikâyesinin benzerliğinden yola çıkarak filmi beş yılda oluşturan Nina Paley, hikayeleri eski bir trajediyi ve modern komediyi harmanlayarak anlatıyor. Berlin Film Festivali’nde 'Özel Mansiyon' ödülüne layık görülen filme, 1920'lerin caz vokalisti Annette Hanshaw da renk katıyor. Karşınızda ?Anlatılmış En Büyük Ayrılık Hikayesi? !", goruntuAdi: "sitasingstheblues"),
            Oneri(adi: "Paprika", detaylari: "Geçtiğimiz yıl dünyadan ayrılan anime ustası Satoshi Kon'un son filmi Paprika, 2006 yılında Venedik Film Festivali'nde yarışma bölümünde dünya prömiyerini yapmış ve birçok animasyon festivalinde gösterilmişti. Terapistlerin, hastalarının rüyalarına giriş yapabilmeyi sağlayacak bir cihazın gelişim aşamasındayken çalınmasıyla olagelen kötü kullanımlar sebebiyle rüya-gerçek ayrımını yapmakta zorlanmaları ve bunun sonucunda yüzleşmek zorunda kaldıkları durumları, bilinçaltının derinlikleri ve psikanalitik ile harmanlayan Paprika, karnaval atmosferindeki rüya alemlerinin rengarenk cümbüşü içerisinde ulaşılması zor bir yaratıcılık sergiliyor. Bu usta işi animenin, rüyalar üzerine yapılmış en etkileyici çalışmalardan biri olduğu ve Christopher Nolan yapıtı Inception (2010)'u oldukça etkilediği söylenebilir.", goruntuAdi: "paprika"),
            Oneri(adi: "Persepolis ", detaylari: "2007 yapımı Marjane Satrapi'nin aynı ismi taşıyan ve çizgi roman olarak yazılmış otobiyografisinin sinemaya uyarlanmasıyla yapılmış animasyon filmi. Film ABD'de Aralık 2007 yılında gösterime sunulmuştur. Filmin süresi 95 dakikadır. Yapıldığı ülke Fransa'dır. Filmin bütçesi 7 milyon 300 bin dolardır.", goruntuAdi: "persepolis"),
            Oneri(adi: "The Wind Rises", detaylari: "Uçaklara bir hayli ilgili olan ve bir gün uzman bir uçak tasarımcısı olmanın hayallerini kuran başkahraman Jiro'nun hikayesini ele alıyor. En büyük idolü ise bu alanda tanınmış bir uzman olan, Alpler'in ötesindeki Caproni'dir. Caproni işlerinin estetik güzelliği ve muazzam teknik becerisiyle bu alanın önde gelen isimlerinden biri olmuştur. Çocukluğundan beri görme sorunları yaşayan Jiro, 1930'ların sonundan önemli bir kurumun uçak departmanına girmeyi başarır. Zaman ilerledikçe başarısı patronlarının da ilgisini çeker ve onu istediği gibi tasarım yapması konusunda özgür bırakmaya karar verir. İkinci Dünya Savaşı başlamak üzeredir ve Jiro'nun hayatında birçok şeyi değiştirecektir. Filmin yönetmen koltuğunda usta sinemacı Hayao Miyazaki bulunuyor.", goruntuAdi: "thewindrises"),
            Oneri(adi: "Inside Out", detaylari: "Küçük bir çocuğun hikayesini anlatıyor. Küçük Riley için hayat, babasının San Francisco'da yeni bir işe başlamasıyla baştan aşağıya değişir. Orta-Batı'daki yaşamını geride bırakan Riley'ı şimdi yeni bir ev, okul ve arkadaşlar beklemektedir. Peki içindeki duyguları o ne söyler? Neşe (Amy Poehler), Korku (Bill Hader), Öfke (Lewis Black), Nefret (Mindy Kaling) ve Üzüntü (Phyllis Smith)... Riley'in zihninin içinde yaşayan, ona günlük hayatında tavsiyeler veren duyguları bu yeni hayata alışırken ufak bir kaosa neden olacaktır. Neşe, Riley'nin en önemli duygusudur ve onu hep pozitif tutmaya çalışır ama diğer duygular bu yeni hayatına uyum sağlama konusunda biraz şaşkındır... Orijinal fikri ve yönetmenliği Pete Docter'a ait olan eğlenceli animasyonun senaristi Michael Arndt. Disney ve Pixar'ın ortak yapımı filmin orijinal seslendirme kadrosunda ise Amy Poehler, Bill Hader, Mindy Kaling, Phyllis Smith ve Lewis Black gibi isimler yer alıyor.", goruntuAdi: "insideout"),
            Oneri(adi: "Frankenweenie", detaylari: "Victor, sevgili köpeği Sparky'yi aniden kaybedince, en iyi dostunu tekrar yaşama döndürmek için bilimden yardım alır ve başarır! Ama yarattığı Sparky orjinalinden birazcık farklıdır. Victor köpeğini evde saklamaya çalışır ama Sparky gün yüzüne çıkınca, Victor'ın çevresindeki herkes bu yeni yaşam ihtimalini keşfetmek için kapışır. Stop-motion animasyonların babası Tim Burton'ın 1984'te çektiği 29 dakikalık kendi kısa filmi Frankenweenie'nin 2011 teknolojisi ile yeniden uyarlaması olan bu yapım, bir oğlan çocuğu ile onun köpeğinin sevimli hikayesini sinema perdesine taşıyor. Fikir babası yönetmeni ve yapımcısı Tim Burton olan projenin senaryosu ise John August'a ait. Siyah-beyaz ve 3 boyutlu olarak çekilen filmin orijinal seslendirme kadrosunda Winona Ryder, Martin Short, Catherine O'Hara, Martin Landau, Charlie Tahan gibi isimler yer alıyor.", goruntuAdi: "frankenweenie"),
            Oneri(adi: "Tokyo Godfathers", detaylari: "İlginç konusuyla 2003 yılının öne çıkan örneklerinden. Yönetmenliğini Satoshi Kon'un gerçekleştirdiği filmde (dikkatli sinemaseverler, kendisini Perfect Blue filminden hatırlayacaktır) üç homeless'ın hayatı mercek altına yatırılıyor. Tokyo sokaklarında kıt kanaat yaşamakta yaşamaya çalışan bu üç talihsiz evsiz -evden kaçan lise öğrencisi Miyuki, transseksüel Hana ve orta yaşlı alkolik Gin- bir Noel Arifesi'nde çöplerin içinde bir bebek bulurlar. Kısmet Hana içindir; zira hep anne olma hayali kurmuş olan Hana, bebeği o gecelik yanlarında tutmak için diğer ikisini ikna eder. Sonraki gün bebeğin annesini bulmak için Tokyo'nun köhne sokaklarından ışıklı caddelerle dolu zengin semtlerine doğru yola çıkarlar. Bu yolculuksa hayatlarının macerası olur; çünkü üçlü kendi geçmişleriyle de yüzleşmek zorunda kalacaklardır. Tokyo Godfathers, komedi ile duygusallığı başarı ile harmanlayan, sevimli ve kaydadeğer bir film.", goruntuAdi: "tokyogodfathers")
        ]
        
        let bilimKurguFilmleri = [
            Oneri(adi: "The Thirteenth Floor", detaylari: "Bir gökdelenin 13. katındaki ofislerinde buluşan yüksek teknoloji dahilesi Douglas Hall ve güzel iş arkadaşı Whitney henüz çok gizli olan, en son yazılımlarını denemektedirler. Olağanüstü bir sanal ortam simülatöründe Douglas, 1930'ların Los Angeles'ine gidip harikulade bir macera yaşamaktadır. Genç adam biraz tehlikeli ve işlerin yolunda gitmediği bir seansı terkedip gerçek hayata döndüğünde tatsız bir sürpriz onu beklemektedir: Şirketin kurucusu ve hepsine ilham veren Hannon Fuller öldürülmüştür. Üstelik hafızasında delikler oluşan Douglas da bir numaralı şüphelidir.", goruntuAdi: "thethirteenthfloor"),
            Oneri(adi: "Deja Vu", detaylari: "Son derece gelişmiş sıra dışı bir teknoloji aracılığı insanların geçmişleri de dahil olmak üzere, tüm yaşamlarını mercek altına alabilen bir sistem üzerine kurulu. Ajan Carlin, bu sistemde bir görev almıştır. New Orleans'ta oluşan bir patlamanın ardından hayatının en çarpıcı soruşturmasına dahil olmak durumunda kalır. Zamanda geriye doğru gitmek koşulu ile yaşanan olayların akışına müdahele etmek. Carlin, patlama olayının takibinde kısa bir zaman diliminin öncesine gittiğinde oldukça riskli bir işe girişmiş olur. Dar bir zaman aralığında olayların akışını değiştirebilmek için elinde bir tek fırsatı mevcuttur.", goruntuAdi: "dejavu"),
            Oneri(adi: "Prometheus", detaylari: "Tekrar bilim-kurgu türüne dönüş yapan kült yönetmen Ridley Scott'ın önderliğinde Alien'ın köklerine yapılan bu yolculuk, hayatın başlangıcına dair araştırma yürüten bir ekibin evrenin en karanlık noktasında yaşadıkları maceralara odaklanıyor. Ekibin insanoğlunun geleceğini korumak adına girdiği bu savaş, her şeyin sonu olabilir... Çekimleri gizlilik içinde yürütülen filmin orijinal hikâyesi Jon Spaihts tarafından yazıldı ve daha sonra Lost'un yaratıcısı Damon Lindelof'un elinden geçti. Kadrosuyla göz dolduran Prometheus'un Alien efsanesiyle aynı DNA'yı taşıdığını, fakat seriden tamamen bağımsız olduğunu söylemek gerekir.", goruntuAdi: "prometheus"),
            Oneri(adi: "Looper", detaylari: "Gelecek zamandayız; 2072'de. Zamanlar arasında yolculuk gerçek olmuş, ama yasa dışı olarak karaborsacıların eline düşmüştür. Teknolojiyi elinde tutanlar ne zaman birinden kurtulmak isterlerse onu 30 yıl geriye, 2042'ye göndererek \"Looper\" adı verilen bir grup suikastçıya öldürmesi için \"paketler\". Bu grupta yer alan suikastçılardan biri olan Joe için 2042'de zengin hayatı gayet yolunda gitmektedir; ta ki karşısına öldürmesi için 2072'den gelen yaşlı Joe çıkıncaya kadar... Rian Johnson'ın yazıp yönettiği bilimkurgu aksiyonunun başrollerini Joseph Gordon-Levitt, Bruce Willis ve Emily Blunt paylaşıyor. Yapımcılar ise Ram Bergman ve James D. Stern.", goruntuAdi: "looper"),
            Oneri(adi: "The Abyss", detaylari: "Soğuk Savaş dönemi sırasında bir Amerikan nükleer denizaltısı bilinmeyen bir düşmanın saldırısına uğrar ve deniz tabanına oturur. Amerikan donanması yakınlardaki bir petrol istasyonunun çalışanlarından olayın sebebini araştırmalarını ister ve onlara destek olarak bir özel tim ve yüksek teknolojiyle donatılmış bir araştırma denizaltısı gönderir. Elde ettikleri veriler ve tesbitleri sonucunda takım 'kaza'nın sebebinin dünya dışı varlıkların saldırısı olabileceği yargısına varır, fakat araştırmalarında ilerleyebilmek için 'Abyss' adı verilen derin sualtı kanyonuna girmek zorundalardır.", goruntuAdi: "theabyss"),
            Oneri(adi: "Equilibrium", detaylari: "Üçüncü Dünya Savaşının yaralarını zor da olsa sarmayı başarabilmiş yakın geleceğin dünyasındayız. Savaşın travmasını üzerinden atamamış olan hakim totaliter sistem, barışı korumak adına insanların duygularını baskı altına almaktadır. Sanatsal nesneler bulundurmak veya sanatla ilgilenmek yasaktır. Duyguları tetikleyecek hareketler ya da açığa vuracak davranışların cezası çok büyüktür. Üst düzey bir güvenlik elemanı olan Rahip John Preston (C. Bale) kurallara karşı gelenleri bulup yok etmekle görevlendirilmiştir. Günü birinde Preston kimliğinden uzaklaşmaya başlar.", goruntuAdi: "equilibrium"),
            Oneri(adi: "Planet of the Apes", detaylari: "Bir uzay gemisi, uzun bir süre boyunca ışık hızıyla, uzayın derinliklerinde seyahat etmiştir. Bu süreç boyunca, teorik olarak dünyada uzun bir süre geçmiştir. Yani, uzay gemisi, dünyaya geri dönerken, teorik olarak geleceğin dünyasına geri dönecektir. İşler tahmin edildiği gibi gitmez ve astronotlar, maymunların egemen olduğu, oldukça bitik bir gezegene inerler. Maymunların zihinsel ve fiziksel açıdan oldukça gelişkin olduğu bu gezegen, buraya tümüyle yabancı olan astronotların başına büyük dertler açacaktır.", goruntuAdi: "planetofapes"),
            Oneri(adi: "Edge of Tomorrow", detaylari: "Yakın gelecekte dünyayı ele geçiren Mimics adlı uzaylı birliği, birçok büyük şehri yok eder ve milyonlarca insanı ölümün eşiğinde bekletir. Dünyada hiçbir ordu, onların hızına, silahlarının gücüne ve de en önemlisi telepati yoluyla emir verme ve uygulama güçlerine ulaşamaz. Artık dünyadaki tüm ordular bu uzaylı sürüsüne karşı güçlerini birleştirmek durumundadır ve bu güç birliği dışında ikinci bir şansları yoktur. Subay Bill Cage daha önce bu savaşlardan hiçbirine katılmamış tecrübesiz bir askerdir ve atıldığı yeni görevi onun için bir nevi intihar anlamına gelmektedir. Beklenen olur; Cage dakikalar içerisinde öldürülür... Fakat bu bir sonu değil, yeni bir başlangıcı doğurur. Cage, sıradışı bir şekilde cehennem gibi bir günde uyanır, kendini kırılması zor bir döngünün içerisinde bulur. Buna göre her seferinde ölüp sonrasında yeniden dirilip aynı savaşı bir kez daha tekrarlamak zorundadır. Her geri dönüşünde daha güçlü, daha zeki ve Mimics'lerle daha kolay başa çıkabilir hale gelse de kendine verilen iş dünyanın en zorlu görevidir. Başrollerini Tom Cruise, Emily Blunt ve Charlotte Riley 'nin paylaştığı filmin yönetmenliğini Doug Liman üstleniyor.", goruntuAdi: "edgeoftomorrow"),
            Oneri(adi: "Gravity", detaylari: "Dr. Ryan Stone zeki bir tıp mühendisidir ve emekliliğinden önce son görevine çıkan yetenekli ve deneyimli astronot Matt Kowalsky'nin yönetimindeki mekikte ilk uzay yolculuğuna çıkar. Herşey yolunda gibi görünürken rutin bir keşif yürüyüşü sırasında bir felaket yaşanır. Mekik çarpan bir cisim sonucu paramparça olur. İki bilim insanı uzay boşluğunda yapayalnız kalırlar. Yeryüzü ile iletişimleri tamamen kopmuştur ve sonsuz karanlıkla başbaşadırlar. Şimdi korkunun yerini panik alır, üstelik var olan sınırlı oksijenleri de gitgide tükenmektedir. İkili eve, dünyaya dönüş yolunu bulabilecek midir? Tu Mamá También, Son Umut, Harry Potter ve Azkaban Tutsağı gibi filmlerin yönetmeni ve ortak senaristi olarak tanıdığımız Meksikalı sinemacı Alfonso Cuarón'ın yönetmenliğini üstlendiği bilim-kurgu geriliminin başrollerini ise Sandra Bullock ve George Clooney paylaşıyor.", goruntuAdi: "gravity"),
            Oneri(adi: "Star Trek", detaylari: "Bir zamanların çok sevilen kahramanları bu kez gençlik yılları ile karşımızda. Güç ve cesaret, Atılgan ve ekibinin elindedir elbette. Evren tehdit altındadır ve geleceği parlak görünmez. Bu durum ile mücadele vermesi beklenen de elbette Atılgan ve ekibidir. Türlü tehlikelere göğüs germeleri gerekecek olan Kaptan Kirk ve Spock arasında mücadele de en keskin hali ile sürecektir. Dünya ile derdi olup da intikamın izini süren kötü ruhlu güçler karşında Atılgan ve ekibi ne kadar başarılı olacaklardır? Star Trek macerasının kahramanlarının gençlik yıllarından dem vuran film, Oscar ödüllü olup J.J. Abrams'ın emeği.", goruntuAdi: "startrek"),
            Oneri(adi: "The Matrix", detaylari: "Saygın bir yazılım şirketinde çalışan Thomas Anderson (Keanu Reeves), gecelerini \"Neo\" adı altında program kırarak ve Matrix'i araştırarak geçirir. Esrarengiz şekilde Trinity (Carrie Ann Moss) ve Morpheus (Laurence Fishburne) ile tanışan Neo, yaşadığı dünyanın aslında beyninde gerçekleşen bir simulasyon olduğu gerçeğini öğrendikten sonra ordan kurtarılır ve Morpheus'un önderliğindeki ekibe katılır. Neo gerçek dünyada ilk nefesini aldıktan sonra simulasyona tekrar girerek Matrix'in ne olduğunu kavrayacak ve kurtarılma nedenini öğrenerek gelişen olaylar çerçevesinde yeni kimliğini tanımaya çalışacaktır.", goruntuAdi: "thematrix"),
            Oneri(adi: "Inception", detaylari: "Dominick \"Dom\" Cobb (Leonardo DiCaprio) yetenekli bir hırsızdır. Rüya görme anında insanların bilinçaltına girerek önemli sırları çalmaktadır. Son kurbanı Japon işadamı Saito (Ken Watanabe) 'dir. Saito'nun bilinçaltının derinliklerinde dolaşırken ölen karısı Mal'i görür ve çalma işi başarısız olur. Bu durum onu uluslararası bir kaçak yapmıştır. Bundan kurtulması için mükemmel bir fırsat yakalar. Kaybettiği her şeyi geri alabileceği son bir iş. Tabii mükemmel \"Başlangıç\"ı tamamlayabilirse. Bu sefer zihinden bir şey çalınmayacak onun yerine bir fikir yerleştirilecektir.", goruntuAdi: "inception")
        ]
        let korkuFilmleri = [
            Oneri(adi: "The Silence of the Lambs", detaylari: "1992 yılında 7 dalda Oscar'a aday olmuş, yönetmeni ve başrol oyuncularına altın heykelciği getirirken en iyi film ve en iyi senaryo uyarlaması dalında da ödüle hak kazanmıştı. Akademiden mezun olmuş genç FBI ajanı Clarice Starling, FBI ajanı kurbanlarının derilerini yüzen sapık bir katilin elinden bir kadını kurtarmaya çalışır. Clarice, katila ulaşmak için başka bir psikopat olan ünlü doktor Hannibal Lecter ile yakınlaşır. Lecter'dan bilgi alması için önce onun güvenini kazanması gerekmektedir.", goruntuAdi: "thesilenceofthelambs"),
            Oneri(adi: "The Shining", detaylari: "Yazar Jack Torrance'ın, kış sezonunda kapalı olan Overlook Oteli'nin bakımını üstlenerek, ailesiyle birlikte otele taşınması sonrasında gelişen metafiziksel olayları konu alır. Jack'in doğaüstü sezgilere sahip olan küçük oğlu, zamanla otelin içerisinde yalnız olmadıklarını, geçmiş ve gelecekten gelen hayaletlerle birlikte yaşadıklarını görür ve ailesini buna inandırmaya çalışır. Aile bir kar fırtınası sebebiyle dağda konuşlanan bu otelde mahsur kaldığındaysa Jack doğaüstü varlıklar tarafından ele geçirilir ve yavaş yavaş aklını kaybetmeye başlar.", goruntuAdi: "theshining"),
            Oneri(adi: "Funny Games", detaylari: "1997'de gerçekleştirdiği Funny Games orijinal versiyondan sonra, efsanevi yönetmen Haneke bu kez de 2007 yılında Amerikan versiyonu \"Ölümcül Oyunlar\" ile bir kez daha kendi filmini yorumluyor. Ölümcül oyunlarda burjuvaziye olan tiksintinin şiddet yoluyla dışa vurumu söz konusu. Ann, George ve oğulları Georgie kısa bir tatil için göl kenarındaki yazlık evlerine giderler. Vardıklarında komşuları Fred ve Eva'da bir gariplik sezerler. Ertesi sabah golf oynamak üzere sözleşmişlerdir. George ve Georgie yelkenli teknelerini tamir ederken, Ann de yemek yapmaya koyulur. Bu sırada Eva'ların misafiri olarak tanıştıkları genç ve kibar görünümlü Peter, Ann'i şüphelendirir.", goruntuAdi: "funnygames"),
            Oneri(adi: "The Conjuring", detaylari: "Konusunu gerçek bir hikayeden alan Korku Seansı, doğaüstü olayları inceleyip aydınlatmaya çalışan dünyaca ünlü çift Ed ve Lorraine Warren'ın karşılaştıkları ürkütücü bir vakayı ele alır. Ed ve Lorraine Warren bir gün Perron ailesinden bir telefon aldıklarında hayatlarının en korkutucu görevine atıldıklarının farkında değildir. Perron ailesinin gözlerden uzak çiftlik evi nedeni bilinmeyen karanlık bir varlık tarafından kuşatılmıştır ve bu nedenle de hayatları tam bir kabusa dönüşmüştür. Bu vakayı çözebileceklerine inanan deneyimli Warren çifti, ne kadar şeytani bir varlıkla karşı karşıya olduklarını çok geç fark edeceklerdir.", goruntuAdi: "theconjuring"),
            Oneri(adi: "The Orphanage", detaylari: "Filmde öksüz ve yetimlerin korku dolu hayatları işleniyor. Laura, çocukluğuna dair en mutlu günlerini deniz kenarındaki bir yetimhanede geçirmiştir. Yetimhanenin çalışanları ve Laura'nın birlikte büyüdüğü arkadaşları ona her zaman ilgi ve şefkat göstermişler, sevgilerini asla esirgememişlerdir. Şimdi, 30 yıl sonra, Laura, kocası Carlos ve 7 yaşındaki oğlu Simon'la çok güzel yıllar geçirdiği yetimhaneye geri dönmüştür. Hayali, uzun süredir kapalı olan yetimhaneyi restore ettikten sonra engelli ve hasta çocuklar için bir yaşam alanı haline getirmektir.", goruntuAdi: "theorphanage"),
            Oneri(adi: "The Descent", detaylari: "Kocası, kızı ve arkadaşları ile birlikte tatile çıkan genç ve hoş bir kadın, trajik bir kazaya şahit olurlar. Aradan bir yıl geçtikten sonra genç kadın yine arkadaşları ile bir gün yürüyüşe çıkar. Bir mağara içinde düşen bir kaya nedeni ile orada mahsur kalırlar. Sahip oldukları donanım yetersizliğinden ötürü hayatta kalmak adına zorlu bir mücadele başlar. Bu sırada da kana susamış yaratıklarla karşılaşırlar. Gruptaki herkes bir takım sebeplerden ötürü birbirleri ile zıt düşerler. Artık herkes tek başınadır. Hayatta kalma yolunda kendilerinden sorumlu olduklarının farkındadırlar.", goruntuAdi: "thedescent"),
            Oneri(adi: "High Tension", detaylari: "Okuldan arkadaş olan Alex ve Marie sınavlarına rahat bir yerde çalışabilmek dinlenmek için Marie'nin ıssız bir yerde olan evine giderler. Gece geç saat varır varmaz yatarlar. Kısa bir süre sonra kapı çalınır ve psikopat bir seri katil içeri dalıp evdekileri öldürmeye başlar. Marie bütün bu olanlara şahit olur ve katil onun odasına bakacağı sırada saklanır. Fakat katil Alex'i bulur ve onu kelepçeler. Marie, Alex'e yardım edeceğine söz verir ve katilden saklanarak hayatlarını kurtarmaya çalışır. Acaba Marie bu zorlu mücadeleden arkadaşıyla sağ kurtulabilecek midir? Acaba her şey göründüğü gibi midir? Şaşırtmacalı, yüksek gerilimi ve ?yüksek tansiyon'uyla, festivaller tarafından ilgi gören bu yapım, gerilimcilerin de yüksek beğenisini topladı.", goruntuAdi: "hightension"),
            Oneri(adi: "Event Horizon", detaylari: "2040 yılında uzaya araştırmalar yapmak üzere gönderilen bir uzay gemisidir. Görevi esnasında kaybolmuştur. Olayın üzerinden geçen yedi senenin ardından bilim insanları bu uzay gemisini aramak ve akıbetini kavramak üzere bir kurtarma gemisi göndermeye karar verirler. Titiz bir şekilde bir araya getirilen ekip, çıkacakları bu karanlık yolculuğun dehşetinden habersizdir. Geriye dönmek, düşündükleri kadar kolay olmayacaktır.", goruntuAdi: "eventhorizon"),
            Oneri(adi: "The Witch", detaylari: "17. yüzyılda İngiltere'de yaşayan William ve Katherine çifti, beş çocuğuyla birlikte ıssız bir ormanın içerisinde hristiyan kurallarına sıkı sıkıya bağlı bir şekilde yaşamaktadır. Aile düzenleri ise beklenmedik garip olayların ortaya çıkmasıyla sarsılmaya başlar. Yeni doğan çocukları Sam, ardında hiçbir iz bırakmadan ortadan kaybolur, büyük kızları Thomasin ilahi sesler duyduğuna inanmaktadır, ikizleri ise tuhaf kafiyeler mırıldanmaya başlar. Bu durumlar ailenin başına gelecek büyük felaketlerin başlangıcı olur. Robert Eggers'in yazıp yönettiği filmin oyuncu kadrosunda Anya Taylor-Joy, Ralph Ineson, Kate Dickie ve Harvey Scrimshaw gibi isimler bulunuyor.", goruntuAdi: "thewitch"),
            Oneri(adi: "The Strangers", detaylari: "Yönetmen Bryan Bertino'nun, çocukluğunda yaşadığı ve etkisinden çıkamadığı bir olayı senaryolaştırarak beyaz perdeye aktardığı bu filmde, Kristin McKay ve James Hoyt adındaki çiftin travması anlatılıyor. McKay ve Hoyt bir dostlarının düğününe katılırlar. Dönüşte, James'in ailesinin yazlık evinde bir gece geçirmeyi planlamaktadırlar. Romantik başlayan geceleri, kimliği belirsiz üç kişinin ortaya çıkması ve hayatlarını bir cehenneme çevirmesiyle devam edecektir. Güvenli sandıkları evleri, bu maskeli yabancılar tarafından terör ortamına çevrilirken, güzelliği dillere destan Liv Tyler gözlere hitap ediyor. Sanatçının bu tip bir gerilim filminde ilk kez yer aldığını da belirtmek gerekir.", goruntuAdi: "thestangers"),
            Oneri(adi: "Dead Silence", detaylari: "Karısının gizemli bir şekilde öldürülmesini araştırmak için yaşadıkları kasabaya yeniden geri dönen Jamie, kendisini bir dolu gizemli olayın ortasında bulacaktır. Testere'nin yönetmeni, senaristi ve yapımcısı olan James Wan'ın yönetip senaryosunu yazdığı film, korku meraklıları için ilgi ile beklenen bir çalışma olacak gibi.", goruntuAdi: "deadsilence"),
            Oneri(adi: "Jeepers Creepers", detaylari: "Trish ve Derry, springbreak tatillerini geçirmek üzere ailelerinin yanına döneceklerdir. Ancak bu tatili daha keyifli kılmak adını yolu uzatmaya ve başka türden bir tatil yapmaya karar verirler. Florida'da çatıştıkları tuhaf bir kamyoncu, kamyonuyla onları ana yolun dışarısına atar. Bir süre sonra da aynı kamyoncunun, bir insan cesedini bir kanalizasyona attığını görürler. Trish ve Derry, tatili bir kenara bırakıp olayın altını kazımaya karar verirler. Bu kararları onları pek de memnun etmeyecektir.", goruntuAdi: "jeeperscreepers")
        ]
        
        let dramFilmleri = [
            Oneri(adi: "Babam ve Oğlum", detaylari: "Babam ve Oğlum'da, 12 Eylül darbesinin yıktığı hayatlardan birinde yetişmektedir küçük Deniz. Annesini henüz doğmadan önce kaybetmiş, bir gazetede yazar olarak çalışan babası tarafından mütevazi bir evde yetiştirilmiştir. Babası dışında tanıdığı tek bir akrabası bile yoktur. Taki babası Sadık, bir gün Deniz'i şaşırtacak bir haberle gelene kadar... Deniz artık babasıyla birlikte, hiç görmediği dedesinin yanında, küçük bir kasabada yaşayacaktır. Köye vardıklarında Sadık yıllar önce küstüğü babasını ilk kez görüyordur. Aralarındaki bu üskünlük kolay kolay geçecek cinsten bir durum değildir. Sadık'ın dönüş sebebini anlamlandıramayan aile bir yandan çok mutluyken diğer yandan tedirgindir de. Zamanla Deniz bu hiç görmediği ailesine alışırken ve her şey düzelmeye başlamışken yaşanan bir dram herkesi derinden etkileyecektir. Son dönem sinemamızın en dokunaklı filmlerinden biri olarak kabul gören Babam ve Oğlum kendi türünde klasikleşmeye aday filmlerden biri.", goruntuAdi: "babamveoglum"),
            Oneri(adi: "Canım Kardeşim", detaylari: "Küçük Kahraman, ağabeyi ve ağabeyinin sadık arkadaşı Halit,birlikte yoksul ama neşeli bir hayat sürdürmektedir. Devamlı bir işleri olmayan ve günlerini daha çok aylaklıkla geçiren bu ikilinin tek amacı Küçük Kahramanın okuması ve hayatını kurtarmasıdır. Parasızlığa rağmen keyifli bir hayat geçiren bu küçük ailenin mutluluğu öğretmenin Kahraman'la ilgili bir gerçeği ortaya çıkarmasıyla son bulur. Yapılan sağlık taramalarının ardından kan kanseri olduğu anlaşılan Kahramanın en büyük isteği ise bir televizyondur. Halit ve ağabey bundan sonra tüm güçlerini bir televizyon alabilmek için harcayacaktır.", goruntuAdi: "canimkardesim"),
            Oneri(adi: "Braveheart", detaylari: "13. yüzyıl İskoçya'sı... İngiliz Kralı Edward, İskoçya'yı da krallığına katmak istemektedir. İngiliz soylularına Prima Nocta; yani topraklarında evlenen her kadınla ilk geceyi geçirme hakkını vererek İskoç halkının ayaklanmasına sebep olur. Çocukken ailesini ve yakınlarını özgür İskoçya uğruna kaybeden William Wallace, yıllar sonra karısı da öldürülünce halkı organize etmeye ve İngilizleri topraklarından atmaya karar verir.", goruntuAdi: "braveheart"),
            Oneri(adi: "Million Dollar Baby", detaylari: "Frankie Dunn ringlerde yaşadığı yıllar boyunca müthiş dövüşçüler yetiştirmiştir. Öğrencisi olan boksörlere öğrettiği en önemli ders ise kendi hayatı için de temel kabul ettiği, her şeyin üzerinde kendini korumaktır. Onu kızından soğutan ve uzak tutan acı deneyimi yüzünden uzun zamandır hiç kimse ile yakın olmamaya çalışmaktadır. Tek arkadaşı Scrap, onun spor salonuna göz kulak olmakta ve kaba dış görünümünün altında 23 yıldır yakasını bırakmayan bir affedilme beklentisi olduğunu bilmektedir ve bir gün Maggie Fitzgerald spor salonuna gelir.", goruntuAdi: "milliondollarbaby"),
            Oneri(adi: "Turtles Can Fly", detaylari: "Irak - Türkiye sınırında, Amerikan işgali altındaki bir Kürt mülteci kampında yaşayan 13 yaşındaki Satellite, bir yandan çat pat bildiği İngilizce'si ile uydudan duyduğu haberleri köylülere tercüme ederken, diğer yandan patlamamış olan kara mayınlarını toplayarak geçinmeye çalışan diğer çocukların liderliğini yapmaktadır.", goruntuAdi: "turtlescanfly"),
            Oneri(adi: "Kız Kardeşim Mommo", detaylari: "Dokuz yaşında bir çocuk; hem ağabey, hem baba, hem anne, hem de bir bilge olabilir mi? Ayşe için olur. Hatta hiçbir şeyden korkmayan bir ağabeydir o. Annesiz iki çocuğun içinizi ısıtacak, kimi zaman gözünüzü yaşartacak öyküsü. Hem de gerçek. Yalın bir dille köyü, köyün insanlarını, kardeşlerin ilişkini anlatan film, sürpriz bir finalle bitiyor. 2009 İstanbul Film Festivali programında yer alan film, 59. Berlin Uluslararası Film Festivali 'nde de gösterilen iki Türk filminden biri oldu.", goruntuAdi: "kizkardesimmommo"),
            Oneri(adi: "Titanic", detaylari: "Dünyanın hatırlamak istemediği türden felaketlerden olan 'Titanik faciası', dev prodüksiyonların yönetmeni James Cameron tarafından çekilen görkemli bir film. Teknolojinin son sürat ilerlediği bir dönemde, insanlar üstesinden gelemeyecekleri hiç bir sorun olamayacağına inanmaya başlamışlardır. 'Titanic' adlı dev transatlantik ise, insanlığın doğaya karşı gövde gösterisi gibidir. Bu 'Düşler Gemisi' nin yolcuları arasında Avrupa`da birkaç yıl geçirdikten sonra Amerika'ya dönmekte olan, Jack adlı genç bir ressam ile nişanlısı ve annesiyle Philadelphia`ya giden Rose adlı genç bir kız da vardır. İki genç, şans eseri tanışacak, aralarındaki sınıf farkına aldırmaksızın birbirlerine yakınlaşacaktır. Bu arada doğa insanoğlunun günden güne artan kibirine bir nokta koymayı planlamaktadır. Yola çıkılmasından dört buçuk gün sonra, 10 Nisan 1912'de, Titanic iki saat kırk dakika süren ve sulara gömülmesiyle son bulan, hazin olayların başlamasına neden olacak buz dağına çarpacaktır. James Cameron'un, seyirciye bir zaman makinesiyle yolculuk ettiği hissini uyandırırcasına gerçeğe yakın filmi 'Titanic' tam 14 dalda Oscar adayı olarak 'En İyi Film' dahil 11 ödülü kazanmıştı. Efsanevi film 15 yıl sonra 3D teknolojisi ile 6 Nisan 2012'de yeniden sinemalara dönüyor.", goruntuAdi: "titanic"),
            Oneri(adi: "Hugo", detaylari: "Hugo Cabret Paris tren istasyonunun duvarları arasında gizlice yaşayan ve saatlerin düzgün çalışmasından sorumlu olan kimsesiz bir çocuktur. Bir müze yangınında saat ustası babasını kaybeden Hugo, ondan yadigar kalan bir \"automaton\"u da gizlice tamir etmeye çalışır. Bu arada Paris tren istasyonunun güvenlik görevlisinden sürekli saklanır, oyuncak dükkanı sahibi Bay Georges'tan (Méliés) çaktırmadan mekanik parça aşırır. Bir gün Georges'un manevi kızı Isabella ile tanışması Hugo'ya yeni bir dünyanın kapılarını daha açacaktır... Usta yönetmen Martin Scorsese'nin de ilk 3D denemesi olan Hugo Brian Selznick'in \"The Invention of Hugo Cabret\" adlı çocuk romanından uyarlanan bir yapım. 2008 Caldecott nişanına sahip olan bu kitabın esas ilham kaynağı ise sinemanın babası olarak sayılabilecek Georges Méliés filmleri ve yönetmenin mekanik figür koleksiyonları... Sinema tarihine bir saygı duruşu niteliğinde de olan Hugo, 84. Akademi Ödülleri'nde En İyi Film de dahil olmak üzere tam 11 dalda aday.", goruntuAdi: "hugo"),
            Oneri(adi: "Eşkıya", detaylari: "Eşkıya, hapse düşmesine neden olan arkadaşının peşine düşen bir adamın hikayesini anlatıyor. 35 yıl önce Cudi dağlarında bir grup eşkiya yakalandı ve hapse atıldı. Yıllar içinde kimi hastalıktan, kimi hesaplaşma sonucu öldü. Biri hariç... 35 yıl sonra Hapisten çıkınca Baran' ın ilk işi köyüne dönmek olur. Yıllar önce hapse girmesine en yakın arkadaşının sebep olduğunu öğrenir. Bu en yakın arkadaşı onun çocukluk aşkını alarak İstanbul' a gitmiştir. Baran da onu bulmak üzere İstanbul'un yolunu tutar. Yavuz Turgul'un senaryosunu yazıp yönetmenliğini üstlendiği Türkiye sinemasının unutulmaz filmlerinden Eşkıya'nın başrollerinde Şener Şen, Uğur Yücel, Şermin Hürmeriç ve Yeşim Salkım bulunuyor.", goruntuAdi: "eskiya"),
            Oneri(adi: "The Green Mile", detaylari: "Mucizeler hiç beklemediğiniz yerlerde gerçekleşebilir, hatta Cold Mountain Cezaevinin bir hücresinde bile...John Coffey, doğaüstü güçlere sahip bir mahkumdur. Tom Hanks ise bu hapishanede görevlidir. Yeşil Yol, hastalık, ölüm, iyilik ve kötülük üzerine etkileyici bir öyküyle King'in güçlü kalemini ve Tom Hanks'ın oyunculuğunu birleştiren, duygu yüklü bir film. Yönetmen Darabont, romana sadık kalarak öykünün büyülü duygusallığını beyaz perdeye taşıyor. Bu film, dört dalda Oscar ödüllerine aday gösterilmişti.", goruntuAdi: "thegreenmile"),
            Oneri(adi: "About Elly", detaylari: "Ahmad, Almanya'da yıllar boyu yaşadıktan sonra, İran'ı ziyaret etmeye karar verir. Üniversiteden eski arkadaşları, Ahmad'ın gelişi onuruna Hazar Gölü kıyısında hep birlikte üç gün geçirecekleri bir tatil planlarlar. Bu tatili düzenlemek, gruptaki kadınlardan birinin, neşeli Sepideh'ın sorumluluğundadır. Sepideh, gruptaki arkadaşlarının haberi olmaksızın, kızının anaokulu öğretmeni Elly'yi de davet eder. Almanya'da yaptığı mutsuz evlilikten henüz kurtulmuş olan Ahmad, İranlı bir kadınla bir yuva kurmak istemektedir. Bunu bilen arkadaş grubu, Sepideh'in Elly'yi niçin davet ettiğini yavaş yavaş anlarlar. Tatilin ikinci gününde, her şey iyi gidiyor gibi gözükürken bir olay neticesinde Elly ortadan kaybolur.", goruntuAdi: "aboutelly"),
            Oneri(adi: "Hotel Rwanda", detaylari: "Dünyanın öbür ucundaki bir ülkede, Rwanda'da 1994'de Hutu'larla Tutsi'ler arasında çıkan savaş yüzünden yüzbinlerce insan öldürülür. Sokaklar adeta bir ceset tarlasına dönmüştür. Tüm dünya yaşanan bu insanlık durumuna parmağını bile kıpırdatmazken, bir otel sahibi olan Paul, 1200 kişinin hayatını kurtarmak için inanılmaz bir özveri gösterir ve otelini adeta bir sığınağa çevirir.", goruntuAdi: "hotelrwanda")
        ]
        
        
        func onerileriGetir(kategori : String) -> [Oneri] {
            
            switch kategori {
            case "Aksiyon" :
                return aksiyonFilmleri
            case "Animasyon" :
                return animasyonFilmleri
            case "Bilim-Kurgu" :
                return bilimKurguFilmleri
            case "Dram" :
                return dramFilmleri
            case "Komedi" :
                return komediFilmleri
            case "Korku" :
                return korkuFilmleri
            default :
                return komediFilmleri
            }
            
            
        }

    
    
    
    
}
